### ISSUE TITLE
Allow filtering and sorting by maintainability index

### ISSUE THREAD

**Issue by JeroenDeDauw** [rubik/radon#100]
I have a codebase where everything gets ranked A with the MI command. I'd like to get a list of the lowest scoring code and not be bound to the crude categorization of A B and C. Using option `-s` I can see there are some results with a MI under 50. There is no way to just show those though. Looking at the docs I figured the `-x` option would work, though unfortunately it just takes the category (which I found out by looking at the code here on GitHub, since the docs on the site don't mention this). Similarly, there is no way to sort based on MI.

**Comment by rubik** [comment]
Hi Jeroen, sorry for the super late reply.
Rank is there because there is no point in distinguishing individual MI values. The important thing is the magnitude, and the separation of the three groups is a heuristic established by Visual Studio developers, who found it to be working well enough in practice.
On the other hand, sorting makes sense and I'm adding an option to sort in ascending order.
