### ISSUE TITLE
radon 1.5.0 fails on code with PEP263 encoding statement

### ISSUE THREAD

**Issue by pierre-rouleau** [rubik/radon#115]
Using:  
- Windows 7
- Python  2.7.10
- radon 1.5.0
- installed: colorama-0.3.8 flake8-3.3.0 mccabe-0.6.1 pycodestyle-2.3.1 pyflakes-1.5.0 radon-1.5.0
- RADONFILESCODING environment unset 

With any python source code file that starts with the following line:
`# -*- coding: iso-8859-1 -*-`

Executing `runradon mi ` for the specific python source code file,

radon 1.5.0 reports the following error:  "ERROR: encoding declaration in Unicode string (<unknown>, line 0)"

- Radon 1.4.2 had no problem with the exact same python source code file.
- Trying setting the RADONFILESCODING to various values (UTF-8, iso-8859-1) does not help; other encoding mismatches are simply reported.

-----

**Comment by rubik** [comment]
Can't reproduce with Python 2.7 and radon 1.5.0 on Linux. I'll try it on Windows as soon as I can. Note, however, that there was a bug in relation to how RADONFILESENCODING was used. Could you try with master? (Also, you may have a typo in the env var name.)

**Comment by pierre-rouleau** [comment]
Sorry, the typo is inside my report.  In the command shell I was using:

`set RADONFILESENCODING=ISO-8859-1` or `set RADONFILESENCODING=UTF-8` and `set RADONFILESENCODING=` to get rid of it.

**Comment by pierre-rouleau** [comment]
Also, is this not an issue related to the fact that we are attempting to specify Unicode and then chnging the encoding with the `# -*- coding: iso-8859-1 -*-` line?

**Comment by hagifoo** [comment]
I use same encoding statement (`# coding: utf-8`) and got same error `ERROR: encoding declaration in Unicode string (<unknown>, line 0)`.

Using:
- Mac OS.X 10.11
- python 2.7.12
- radon 1.5.0
- RADONFILESCODING environment unset


I changed `fobj.read()` in `radon.cli.harvest.MIHarvester.gobble` to `fobj.read().encode('utf-8')` and it works (this is not a good solution).

The following is my guess.

----

In `radon.cli.harvest.Harvester.run` , `radon.cli.tools._open` is used to open the file. In `_open`, encoding is specified as `_open_function(path, encoding=_encoding) as f`, thus `f.read()` returns Unicode string.

In `radon.cli.harvest.MIHarvester.gobble`, source is read in `fobj.read()` as UNICODE string (because encoding is already specified) and `mi_visit` get Unicode source and pass it to `ast.parse`.

`ast.parse` seems to try decoding input source using the PEP263 encoding statement, however the source is already decoded as Unicode string and the error is occurred.

----

**Comment by collinstocks-oscar** [comment]
Do you know when to expect this to be released now that it is fixed?
