### ISSUE TITLE
Maintainability index fails when PEP 263 encoding statment is present

### ISSUE THREAD

**Issue by dlocke** [rubik/radon#127]
I created a simple file named test_radon.py

```python
#/usr/bin/env python2
# -*- coding: ascii -*-

def foo():
    return True

```

Radon is able to compute the cyclomatic complexity but fails when trying to compute the maintainability index.

```shell
$ radon --version
2.0.2
$ radon cc -s test_radon.py 
test_radon.py
    F 4:0 foo - A (1)
$ radon mi -s test_radon.py 
test_radon.py
    ERROR: encoding declaration in Unicode string (<unknown>, line 0)
```

Without the encoding line I get the expected results

```shell
$ radon cc -s test_radon.py 
test_radon.py
    F 4:0 foo - A (1)
$ radon mi -s test_radon.py 
test_radon.py - A (100.00)
```

**Comment by thebjorn** [comment]
I can verify that this happens on windows too:
```
(dev) go|c:\srv\lib\dknorway> cat dknorway\__init__.py
# -*- coding: utf-8 -*-

(dev) go|c:\srv\lib\dknorway> radon --version
2.0.2

(dev) go|c:\srv\lib\dknorway> radon mi dknorway\__init__.py
dknorway\__init__.py
    ERROR: encoding declaration in Unicode string (<unknown>, line 0)

(dev) go|c:\srv\lib\dknorway> chcp
Active code page: 65001

(dev) go|c:\srv\lib\dknorway>
```

**Comment by thebjorn** [comment]
The error comes from the call to `ast.parse()` in `radon/metrics.py`. It is passed a unicode string that is read (`fobj.read()`) in `MIHarvester.gobble()`, from a file that is opened using `_open_function(path, encoding=_encoding)` in `radon/cli/tools.py`.

Aside: ..that `_encoding` variable is wrong, since it assumes all files will have the same encoding, which it is guessing is `locale.getpreferredencoding()`.  That's not a bad guess in the absence of other information, but here we have an encoding statement that ought to override...

When `ast.parse()` gets a Unicode string it doesn't want _any_ encoding statements (the file is the same as in my previous comment, containing one line which is the encoding statement):
```
>>> ast.parse(open('dknorway/__init__.py').read().decode('u8'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\python27\Lib\ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 0
SyntaxError: encoding declaration in Unicode string
```
As I see it, there are two possible correct solutions here:
1. parse encoding
    - open the file in binary/bytes mode, 
    - check if the first line is an encoding statement 
       - if yes: strip the first line, decode the rest using the found encoding, and pass the resulting Unicode string to `ast.parse(..)`
       - if no: assume a sensible encoding like `ascii` or `locale.getpreferredencoding()`.
2. let `ast.parse(..)` handle it
    - open the file in binary/bytes mode
    - pass the contents directly to `ast.parse()`

To prove that option 2 works, I changed the content of `dknorway\__init__.py` to:
```
# -*- coding: utf-8 -*-
print u'æøå'
```
and `ast.parse(..)` converts to unicode for "free":
```
>>> ast.parse(open('dknorway/__init__.py', 'rb').read())
<_ast.Module object at 0x02DF7AD0>
>>> t = _
>>> t.body[0].values[0].s
u'\xe6\xf8\xe5'
>>> type(_)
<type 'unicode'>
>>>
```
I've created a PR.

**Comment by rubik** [comment]
Hi @thebjorn!
Thanks for the analysis, it's been useful. I closed your PR because I didn't like the hackish fix of opening the file a second time. You gave me the right ideas though, and I proposed another solution in #130. I'd like to hear what you think. Can you also verify it on Windows? I cannot at the moment.
That fix would solve the issue on Python 3 but the tokenize.open function is not present in Python 2, so we'll have to add it to radon manually.

**Comment by thebjorn** [comment]
Hi @rubik , glad to help :-)  I left a comment on #130 regarding the bare except and the Py2 issue. Other than that it looks ok. I'll try it out on win/py2.7 later today to verify.
