### ISSUE TITLE
Report error if the input doesn't exists

### ISSUE THREAD

**Issue by mzfr** [rubik/radon#145]
I have been using radon from a while but just noticed this issue. If you pass a random name to radon it doesn't report something like `File doesn't exists` etc. It just stops.
I think there should be a check for this

**Comment by rubik** [comment]
Which subcommand are you using?

**Comment by mzfr** [comment]
All. 

* `radon cc sjkdnasklas`
* `radon cc sjkdnasklas -a`
* `radon mi sadalskdkaskmld`
* `radon raw askjklasklalsmdls`

**Comment by rubik** [comment]
@mzfr This is a consequence of using `os.walk`, which returns a generator that does not yield anything if the path does not exist.

More importantly:
* Radon analyzes files as they are found. This means that if you provide the path to a directory Radon will walk into the directory analyzing Python files as they are found.
* Radon accepts multiple paths from the command line.

Therefore, if one of the paths does not exist, it is unreasonable to stop with an error since (i) it will have already analyzed all the previous files and (ii) there may still be files to analyze. I hope this clears it up.
