### ISSUE TITLE
radon failed when using python type annotations

### ISSUE THREAD

**Issue by rsrdesarrollo** [rubik/radon#146]
Hi,

I have a problem when I try to calculate cc on a python file with type annotations.

For example, this file: 

```
def foo(bar: int):
    return bar
```

Gives me this error:

```
host:/tmp~ radon cc -s script.py
script.py
    ERROR: invalid syntax (<unknown>, line 1)
```

I'm using **Python 3.6.5** and **radon 2.2.0**

**Comment by rubik** [comment]
Radon never executes the file, but it parses the syntax into an AST using the `ast` module. So if you get a SyntaxError it's because the Python version that is executing Radon does not support the syntax in the file. I'm fairly sure you are using Python 2 for Radon.

I just tried your example on Python 3.7 and it works as expected:
```
$ radon cc a.py
a.py
    F 1:0 foo - A
```

**Comment by rsrdesarrollo** [comment]
OK, I'm closing this issue because is related only with my **pyenv** environment.
