### ISSUE TITLE
summary not shown when using --json flag

### ISSUE THREAD

**Issue by lole-elol** [rubik/radon#228]
When i am using radon to get the metrics on multiple files i dont get the summary when i export it to a json file
radon raw --json -s --output-file out.json files0_*.py

**Comment by rubik** [comment]
Correct, the JSON export does not include the summary. At this time the summary needs to be calculated from the JSON output. I have updated the documentation and the CLI help text to clarify this.

**Comment by lole-elol** [comment]
Maybe we can add that feature that the summary is exported to the Json in the future ?

Or do you, @rubik  think that this is not a good idea.

Also i can see myself to contibute this feature to radon.

**Comment by rubik** [comment]
@lole-elol I would be open to adding that, the problem is that currently the JSON structure is not flexible: all paths are top-level keys in the object, and so there's no room for the summary, unless we use a special key (a hacky solution and does not preserve the logical structure) or we update the structure (undesirable because we would break code that is already using it).

The root issue is that the JSON structure that was chosen initially wasn't very flexible.
