### ISSUE TITLE
Missing Python 3.5 Category

### ISSUE THREAD

**Issue by impredicative** [rubik/radon#98]
Is there any reason why `Python :: 3.5` is not listed under Categories on the [pypi](https://pypi.python.org/pypi/radon) page? Better yet, compare with Categories for the entries for [pycodestyle](https://pypi.python.org/pypi/pycodestyle) and [pylint](https://pypi.python.org/pypi/pylint).

**Comment by rubik** [comment]
Yes, the reason is that I forgot to add it. Thanks for the reminder. The other categories are very similar to the packages you mentioned. The most important ones like `Environment :: Console`, `Topic :: Software Development :: Quality Assurance`, `Topic :: Utilities`, `Intended Audience :: Developers` are all there.

**Comment by rubik** [comment]
Fixed in https://github.com/rubik/radon/commit/aba436f297671ce3e44151a4a91627785b89974c, thanks!
